image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup project
    init: >
      sudo pip3 install poetry && 
      curl https://raw.githubusercontent.com/IgnisDa/printr/main/get-printr.sh | sh -s -- --yes && 
      bash -c "/workspace/Resourceium/.devcontainer/setup-storage" && 
      git config --global pull.rebase true && 
      poetry config virtualenvs.in-project true &&
      gp sync-done setup

  - name: Setup dependencies
    init: gp sync-await setup
    command: >
      just setup &&
      gp sync-done deps

  - name: Run servers
    init: gp sync-await deps
    command: just

  - name: Test
    init: /ide/node/bin/gitpod-node --inspect=9228 test.js

ports:
  - port: 3000
    visibility: public
  - port: 8080
    visibility: public
  - port: 8000
    visibility: public

vscode:
  extensions:
    - redhat.java
    - octref.vetur
    - bradlc.vscode-tailwindcss
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - mhutchie.git-graph
    - cweijan.vscode-database-client2
    - ms-python.python
